[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "DriverNet"
version = "0.1.0"
description = "A deep learning pipeline for detecting driver distraction."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "kaggle>=1.7.4.5",
    "lightning>=2.5.5",
    "matplotlib>=3.9.4",
    "numpy>=2.0.2",
    "pandas>=2.3.3",
    "pyyaml>=6.0.3",
    "scikit-learn>=1.6.1",
    "seaborn>=0.13.2",
    "tensorboard>=2.20.0",
    "torch>=2.8.0",
    "torchmetrics>=1.8.2",
    "torchvision>=0.23.0",
    "tqdm>=4.67.1",
    "omegaconf>=2.3.0",
    "matplotlib-inline>=0.2.1",
    "finetuning-scheduler>=2.9.0",
    "cloud-tpu-client>=0.10",
    "opencv-python>=4.11.0.86",
    "pillow>=12.0.0",
    "segment-anything",
    "transformers>=4.57.1",
    "ultralytics>=8.3.225",
]

[tool.setuptools.packages.find]
where = ["."]

[tool.uv.sources]
segment-anything = { git = "https://github.com/facebookresearch/segment-anything.git" }

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
]

[project.scripts]
download-data = "scripts.download_data:main"
check-data = "scripts.test_datamodule:main"
test-teacher = "scripts.test_teacher_model:main"
