global:
    seed: 42
    out_dir: "output"

trainer:
    max_epochs: 10
    accelerator: auto
    devices: auto
    precision: "16-mixed"
    strategy: "auto"

model:
    teacher:
        name: "vit_b_16"
        num_classes: 10
        pretrained: true
        lr: 3e-4
        weight_decay: 5e-4
        scheduler: "onecycle"
        cons_weight: 0.2
        cp_weight: 0.05
        max_logit_norm: null

    student:
        name: "resnet151"
        num_classes: 10
        pretrained: true
        lr: 3e-4
        weight_decay: 5e-4
        scheduler: "onecycle"
        cons_weight: 0.2
        cp_weight: 0.05
        max_logit_norm: null

data:
    original_data_dir: "input/original/train"
    processed_data_dir: "input/processed/train"
    csv_path: "input/driver_imgs_list.csv"
    batch_size: 128
    num_workers: 4
    pin_memory: True
    persistent_workers: True
    image_size: 224
    flip_p: 0.2
    validation_split: 0.2

data_test:
    original_data_dir: "input/original/train"
    processed_data_dir: "input/processed/train"
    predict_dir: "input/original/test"
    csv_path: "input/driver_imgs_list.csv"
    batch_size: 64
    num_workers: 4
    pin_memory: True
    persistent_workers: True
    image_size: 224
    flip_p: 0.2
    validation_split: 0.2

