global:
    seed: 42
    out_dir: "output"

trainer:
    max_epochs: 30
    accelerator: auto
    devices: auto
    precision: "bf16-mixed"
    strategy: "auto"

model:
    name: "resnet50_depthg"
    num_classes: 10
    pretrained: true
    lr: 3e-4
    image_size: 224
    weight_decay: 5e-2
    scheduler: "onecycle"
    label_smoothing: 0.0
    consistency_loss_type: "kd"
    temperature: 5.0
    max_logit_norm: 10.0
    ema_decay: 0.999
    ema_warmup_steps: 100
    consistency_rampup_steps: 0.2
    final_consistency_weight: 1.0

data:
    original_data_dir: "../input/original/train"
    depth_data_dir: "../input/processed_depth/train"
    csv_path: "../input/driver_imgs_list.csv"
    batch_size: 256
    num_workers: 12
    pin_memory: True
    persistent_workers: True
    prefetch_factor: 8
    image_size: 224
    validation_split: 0.2
    num_folds: 0
    fold_index: 0

data_test:
    predict_dir: "../input/original/test"
    depth_data_dir: "../input/processed_depth/test"
    batch_size: 512
    num_workers: 8
    pin_memory: True
    persistent_workers: True
    prefetch_factor: 4
    image_size: 224
